
import java.awt.Color;
import java.awt.Font;
import javax.swing.Timer;
import java.sql.*;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marck England
 */
public class Leaderboards extends javax.swing.JFrame {

    /**
     * Creates new form Gacha
     */
    public Leaderboards() {
        initComponents();
        setLocationRelativeTo(null);
        
        leaderboards.getTableHeader().setVisible(false);
        jScrollPane1.getViewport().setBackground(new Color(182,190,215));
        
        leaderboards.getTableHeader().setOpaque(true);
        leaderboards.getTableHeader().setBackground(new Color(182,190,215));
        leaderboards.getTableHeader().setForeground(new Color(255,255,255));
        
        leaderboards.setFont(new Font("UD Digi Kyokasho N-R", Font.BOLD, 24));
        leaderboards.setOpaque(true);
        leaderboards.setBackground(new Color(182,190,215));
        leaderboards.setForeground(new Color(255,255,255));
        leaderboards.setRowHeight(40);
        
        showLeaderboards();
    }
    
    public void showLeaderboards(){
        DBConnection connectNow = new DBConnection();
	Connection connectDB = connectNow.getConnection();
         
        String getUsers = "SELECT user,atscore FROM gachaponacc ORDER BY atscore DESC";
        
        try{
            PreparedStatement statement = connectDB.prepareStatement(getUsers);
            ResultSet rs = statement.executeQuery();
            leaderboards.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            System.out.println("Error!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaderboards = new javax.swing.JTable();
        leaderboardsLabel = new javax.swing.JLabel();
        topup1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gashapon Quiz");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALL-TIME SCORE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(182, 190, 215));

        leaderboards.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 0, 12)); // NOI18N
        leaderboards.setForeground(new java.awt.Color(255, 255, 255));
        leaderboards.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        leaderboards.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leaderboards.setEnabled(false);
        leaderboards.setFocusable(false);
        leaderboards.setGridColor(new java.awt.Color(0, 0, 0));
        leaderboards.setRequestFocusEnabled(false);
        leaderboards.setRowSelectionAllowed(false);
        leaderboards.setShowGrid(false);
        leaderboards.getTableHeader().setResizingAllowed(false);
        leaderboards.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(leaderboards);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 620, 410));

        leaderboardsLabel.setBackground(new java.awt.Color(0, 0, 0));
        leaderboardsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        leaderboardsLabel.setForeground(new java.awt.Color(255, 255, 255));
        leaderboardsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaderboardsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/Leaderboards/lb.png"))); // NOI18N
        leaderboardsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaderboardsLabelMouseClicked(evt);
            }
        });
        jPanel1.add(leaderboardsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 660, 70));

        topup1.setBackground(new java.awt.Color(0, 0, 0));
        topup1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        topup1.setForeground(new java.awt.Color(255, 255, 255));
        topup1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/Leaderboards/frame.png"))); // NOI18N
        topup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topup1MouseClicked(evt);
            }
        });
        jPanel1.add(topup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 650, 460));

        back.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/Quiz/Back button.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 120, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/Leaderboards/BG.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leaderboardsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaderboardsLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_leaderboardsLabelMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void topup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topup1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_topup1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and dcurrencythe form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gacha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable leaderboards;
    private javax.swing.JLabel leaderboardsLabel;
    private javax.swing.JLabel topup1;
    // End of variables declaration//GEN-END:variables
}
