
import java.awt.Color;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marck England
 */
public class Leaderboards extends javax.swing.JFrame {

    /**
     * Creates new form Gacha
     */
    public Leaderboards() {
        initComponents();
        
//        int token = Integer.parseInt(Home.tokens.getText());
//        tokens.setText("Tokens: "+token);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        leaderboardsLabel = new javax.swing.JLabel();
        comingsoonLabel = new javax.swing.JLabel();
        topup1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gacha");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leaderboardsLabel.setBackground(new java.awt.Color(0, 0, 0));
        leaderboardsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        leaderboardsLabel.setForeground(new java.awt.Color(255, 255, 255));
        leaderboardsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaderboardsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/Leaderboards/lb.png"))); // NOI18N
        leaderboardsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaderboardsLabelMouseClicked(evt);
            }
        });
        jPanel1.add(leaderboardsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 660, 70));

        comingsoonLabel.setBackground(new java.awt.Color(0, 0, 0));
        comingsoonLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comingsoonLabel.setForeground(new java.awt.Color(255, 255, 255));
        comingsoonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comingsoonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/Leaderboards/coming soon.png"))); // NOI18N
        comingsoonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comingsoonLabelMouseClicked(evt);
            }
        });
        jPanel1.add(comingsoonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 640, 70));

        topup1.setBackground(new java.awt.Color(0, 0, 0));
        topup1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        topup1.setForeground(new java.awt.Color(255, 255, 255));
        topup1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/Leaderboards/frame.png"))); // NOI18N
        topup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topup1MouseClicked(evt);
            }
        });
        jPanel1.add(topup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 650, 460));

        back.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/Quiz/Back button.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 120, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/Leaderboards/BG.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leaderboardsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaderboardsLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_leaderboardsLabelMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void topup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topup1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_topup1MouseClicked

    private void comingsoonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comingsoonLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comingsoonLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and dcurrencythe form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gacha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel comingsoonLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leaderboardsLabel;
    private javax.swing.JLabel topup1;
    // End of variables declaration//GEN-END:variables
}
